/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agentiemodelling;

/**
 *
 * @author Edd
 */
public class AddModelForm extends javax.swing.JFrame {

    /**
     * Creates new form AddModelForm
     */
    
    public AddModelForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Nume = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Prenume = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CNP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Data_nastere = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Oras = new javax.swing.JTextField();
        I_tata = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Greutate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Inaltime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Bust = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Solduri = new javax.swing.JTextField();
        Talie = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cul_ochi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Nr_tel = new javax.swing.JTextField();
        Cul_par = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Salariu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Data_angajarii = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Autocaracterizare = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Nume.setText("Daniela");
        Nume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nume");

        Prenume.setText("Ionescu");
        Prenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenumeActionPerformed(evt);
            }
        });

        jLabel2.setText("Prenume");

        CNP.setText("2234567890123");
        CNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNPActionPerformed(evt);
            }
        });

        jLabel3.setText("CNP");

        Data_nastere.setText("1994-07-14");
        Data_nastere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_nastereActionPerformed(evt);
            }
        });

        jLabel4.setText("Data nastere");

        Oras.setText("Botosani");
        Oras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrasActionPerformed(evt);
            }
        });

        I_tata.setText("A");
        I_tata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_tataActionPerformed(evt);
            }
        });

        jLabel5.setText("Oras");

        jLabel6.setText("Initala tata");

        Greutate.setText("60");
        Greutate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreutateActionPerformed(evt);
            }
        });

        jLabel7.setText("Greutate (kg)");

        Inaltime.setText("170");
        Inaltime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InaltimeActionPerformed(evt);
            }
        });

        jLabel8.setText("Inaltime (cm)");

        Bust.setText("65");
        Bust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BustActionPerformed(evt);
            }
        });

        jLabel9.setText("Bust (cm)");

        Solduri.setText("95");
        Solduri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolduriActionPerformed(evt);
            }
        });

        Talie.setText("88");
        Talie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TalieActionPerformed(evt);
            }
        });

        jLabel10.setText("Solduri (cm)");

        jLabel11.setText("Talie (cm)");

        Cul_ochi.setText("Albastri");
        Cul_ochi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cul_ochiActionPerformed(evt);
            }
        });

        jLabel13.setText("Culoare ochi");

        Nr_tel.setText("0794321234");
        Nr_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nr_telActionPerformed(evt);
            }
        });

        Cul_par.setText("Roscat");
        Cul_par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cul_parActionPerformed(evt);
            }
        });

        jLabel15.setText("Numar telefon");

        Salariu.setText("3000");
        Salariu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalariuActionPerformed(evt);
            }
        });

        jLabel17.setText("Salariu (RON)");

        Data_angajarii.setText("2010-09-23");
        Data_angajarii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_angajariiActionPerformed(evt);
            }
        });

        jLabel19.setText("Autocaracterizare");

        jLabel21.setText("Data angajarii");

        jLabel22.setText("Culoare par");

        jLabel12.setText("Introdu datele in casetele de mai jos si apasa enter dupa fiecare data introdusa");

        Autocaracterizare.setColumns(20);
        Autocaracterizare.setRows(5);
        Autocaracterizare.setText("Asta sunt eu");
        jScrollPane2.setViewportView(Autocaracterizare);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nume)
                            .addComponent(Prenume)
                            .addComponent(CNP)
                            .addComponent(I_tata)
                            .addComponent(Data_nastere)
                            .addComponent(Oras)
                            .addComponent(Greutate)
                            .addComponent(Inaltime)
                            .addComponent(Talie)
                            .addComponent(Bust)
                            .addComponent(Solduri))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel13))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Cul_par, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cul_ochi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nr_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Salariu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Data_angajarii, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(44, 44, 44))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(I_tata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Data_nastere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Oras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cul_par, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cul_ochi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nr_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Data_angajarii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Salariu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Greutate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inaltime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Talie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Solduri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeActionPerformed

    }//GEN-LAST:event_NumeActionPerformed

    private void PrenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenumeActionPerformed

    private void CNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNPActionPerformed

    private void Data_nastereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_nastereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data_nastereActionPerformed

    private void OrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrasActionPerformed

    private void I_tataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_tataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_tataActionPerformed

    private void GreutateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreutateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GreutateActionPerformed

    private void InaltimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InaltimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InaltimeActionPerformed

    private void BustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BustActionPerformed

    private void SolduriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolduriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SolduriActionPerformed

    private void TalieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TalieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TalieActionPerformed

    private void Cul_ochiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cul_ochiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cul_ochiActionPerformed

    private void Nr_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nr_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nr_telActionPerformed

    private void Cul_parActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cul_parActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cul_parActionPerformed

    private void SalariuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalariuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalariuActionPerformed

    private void Data_angajariiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_angajariiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data_angajariiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddModelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddModelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddModelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddModelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddModelForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Autocaracterizare;
    public javax.swing.JTextField Bust;
    public javax.swing.JTextField CNP;
    public javax.swing.JTextField Cul_ochi;
    public javax.swing.JTextField Cul_par;
    public javax.swing.JTextField Data_angajarii;
    public javax.swing.JTextField Data_nastere;
    public javax.swing.JTextField Greutate;
    public javax.swing.JTextField I_tata;
    public javax.swing.JTextField Inaltime;
    public javax.swing.JTextField Nr_tel;
    public javax.swing.JTextField Nume;
    public javax.swing.JTextField Oras;
    public javax.swing.JTextField Prenume;
    public javax.swing.JTextField Salariu;
    public javax.swing.JTextField Solduri;
    public javax.swing.JTextField Talie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
