/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agentiemodelling;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Edd
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
            /*
        Initialize all the variables
        */
        //Tabela Model
    	int ID_model, Greutate, Inaltime, Talie, Bust, Solduri, Salariu;
    	String Nume, Prenume, CNP, I_tata, Data_nastere, Oras, Cul_par, Cul_ochi, Nr_tel, Data_angajarii, Autocaracterizare;
    	//Tabela Eveniment
    	int ID_eveniment, Editie;
    	String Nume_eveniment, Data, Locatie, Tip, Descriere;
    	//Tabela Participare
    	int ID_participare;
    	//Tabela Parteneri_evenimente
    	int ID_parteneri_evenimente;
    	String Nume_parteneriat, Tip_parteneriat;
        
        //All the forms
        AddModelForm addModel = new AddModelForm();
        SuccesForm succesMessage = new SuccesForm();
        AddEventForm addEvent = new AddEventForm();
        EditModelForm editModel = new EditModelForm();
        EditEventForm editEvent = new EditEventForm();
        AdminLoginPanel adminLoginPanel = new AdminLoginPanel();
        
        //Pentru editare
        String[] ListOfSelectedModels;
        String[] ListOfSelectedEvents;
       
    
    public MainForm() {
        initComponents();
        
        //My shitty job
        ListOfSelectedModels = new String[6];
        int i = 0;

        ResultSet res = Command.CustomQuery("SELECT ID_model, Nume, Prenume FROM `model`");
        try {
            while (res.next()){
                ListOfSelectedModels[i] = res.getString("ID_model") + " " + res.getString("Nume") + " " + res.getString("Prenume") + ", ";
                i++;
            }
        }catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
         }
        SelectModelToEdit.setModel(new javax.swing.DefaultComboBoxModel<>(ListOfSelectedModels));
        
        ListOfSelectedEvents = new String[6];
        int j = 0;

        ResultSet ress = Command.CustomQuery("SELECT ID_eveniment, Nume FROM `evenimente`");
        try {
            while (ress.next()){
                ListOfSelectedEvents[j] = ress.getString("ID_eveniment") + " " + ress.getString("Nume") + ", ";
                j++;
            }
        }catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
         }
        SelectEventToEdit.setModel(new javax.swing.DefaultComboBoxModel<>(ListOfSelectedEvents));
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        addModelButton = new javax.swing.JButton();
        finishAddingButton = new javax.swing.JButton();
        AddEvent = new javax.swing.JButton();
        finishAddingEvent = new javax.swing.JButton();
        EditModel = new javax.swing.JButton();
        FinishEditingModel = new javax.swing.JButton();
        SelectModelToEdit = new javax.swing.JComboBox<>();
        EditEvent = new javax.swing.JButton();
        FinishEditingEvent = new javax.swing.JButton();
        SelectEventToEdit = new javax.swing.JComboBox<>();
        DeleteModel = new javax.swing.JButton();
        deleteEvent = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        adminPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nume1 = new javax.swing.JLabel();
        Data_nastere1 = new javax.swing.JLabel();
        Greutate1 = new javax.swing.JLabel();
        Salariu1 = new javax.swing.JLabel();
        Data_angajarii1 = new javax.swing.JLabel();
        Data_angajarii2 = new javax.swing.JLabel();
        Salariu2 = new javax.swing.JLabel();
        Greutate2 = new javax.swing.JLabel();
        Data_nastere2 = new javax.swing.JLabel();
        Nume2 = new javax.swing.JLabel();
        AfiseazaModele = new javax.swing.JButton();
        Nume3 = new javax.swing.JLabel();
        Data_nastere3 = new javax.swing.JLabel();
        Greutate3 = new javax.swing.JLabel();
        Salariu3 = new javax.swing.JLabel();
        Data_angajarii3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AfiseazaEvenimente = new javax.swing.JButton();
        Tip1 = new javax.swing.JLabel();
        Locatie1 = new javax.swing.JLabel();
        Editie1 = new javax.swing.JLabel();
        Data1 = new javax.swing.JLabel();
        NumeEveniment1 = new javax.swing.JLabel();
        Parteneri1 = new javax.swing.JLabel();
        Parteneri2 = new javax.swing.JLabel();
        NumeEveniment2 = new javax.swing.JLabel();
        Data2 = new javax.swing.JLabel();
        Editie2 = new javax.swing.JLabel();
        Locatie2 = new javax.swing.JLabel();
        Tip2 = new javax.swing.JLabel();
        Locatie3 = new javax.swing.JLabel();
        Editie3 = new javax.swing.JLabel();
        Data3 = new javax.swing.JLabel();
        NumeEveniment3 = new javax.swing.JLabel();
        Parteneri3 = new javax.swing.JLabel();
        Tip3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addModelButton.setText("Add Model");
        addModelButton.setActionCommand("addModel");
        addModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModelButtonActionPerformed(evt);
            }
        });

        finishAddingButton.setText("Finish adding");
        finishAddingButton.setActionCommand("finishAdding");
        finishAddingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishAddingButtonActionPerformed(evt);
            }
        });

        AddEvent.setText("Add Event");
        AddEvent.setActionCommand("addModel");
        AddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventActionPerformed(evt);
            }
        });

        finishAddingEvent.setText("Finish adding");
        finishAddingEvent.setActionCommand("finishAdding");
        finishAddingEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishAddingEventActionPerformed(evt);
            }
        });

        EditModel.setText("Edit Model");
        EditModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditModelActionPerformed(evt);
            }
        });

        FinishEditingModel.setText("Finish editing");
        FinishEditingModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishEditingModelActionPerformed(evt);
            }
        });

        SelectModelToEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1, item2, item3", "item4" }));
        SelectModelToEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectModelToEditActionPerformed(evt);
            }
        });

        EditEvent.setText("Edit Event");
        EditEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEventActionPerformed(evt);
            }
        });

        FinishEditingEvent.setText("Finish editing");
        FinishEditingEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishEditingEventActionPerformed(evt);
            }
        });

        SelectEventToEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1, item2, item3", "item4" }));
        SelectEventToEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectEventToEditActionPerformed(evt);
            }
        });

        DeleteModel.setText("Delete Model");
        DeleteModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteModelActionPerformed(evt);
            }
        });

        deleteEvent.setText("Delete Event");
        deleteEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEventActionPerformed(evt);
            }
        });

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        adminPanel.setText("Admin Panel");
        adminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPanelActionPerformed(evt);
            }
        });

        jLabel1.setText("Modele");

        Nume1.setText("Nume");

        Data_nastere1.setText("Data nasterii");

        Greutate1.setText("Greutate");

        Salariu1.setText("Salariu");

        Data_angajarii1.setText("Data Angajarii");

        Data_angajarii2.setText("Data Angajarii");

        Salariu2.setText("Salariu");

        Greutate2.setText("Greutate");

        Data_nastere2.setText("Data nasterii");

        Nume2.setText("Nume");

        AfiseazaModele.setText("Afiseaza Modele");
        AfiseazaModele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfiseazaModeleActionPerformed(evt);
            }
        });

        Nume3.setText("Nume");

        Data_nastere3.setText("Data nasterii");

        Greutate3.setText("Greutate");

        Salariu3.setText("Salariu");

        Data_angajarii3.setText("Data Angajarii");

        jLabel2.setText("Evenimente");

        AfiseazaEvenimente.setText("Afiseaza Evenimente");
        AfiseazaEvenimente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfiseazaEvenimenteActionPerformed(evt);
            }
        });

        Tip1.setText("Tip");

        Locatie1.setText("Locatie");

        Editie1.setText("Editie");

        Data1.setText("Data");

        NumeEveniment1.setText("Nume");

        Parteneri1.setText("Parteneri");

        Parteneri2.setText("Parteneri");

        NumeEveniment2.setText("Nume");

        Data2.setText("Data");

        Editie2.setText("Editie");

        Locatie2.setText("Locatie");

        Tip2.setText("Tip");

        Locatie3.setText("Locatie");

        Editie3.setText("Editie");

        Data3.setText("Data");

        NumeEveniment3.setText("Nume");

        Parteneri3.setText("Parteneri");

        Tip3.setText("Tip");

        jButton1.setText("Afiseaza");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Partenerii care au participat la evenimentul in care a venit modelul cel mai inalt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finishAddingEvent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FinishEditingEvent)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Refresh)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Data_nastere2)
                                            .addComponent(Greutate2)
                                            .addComponent(Salariu2)
                                            .addComponent(Data_angajarii2)
                                            .addComponent(Nume2))
                                        .addGap(107, 107, 107)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Data_nastere3)
                                            .addComponent(Greutate3)
                                            .addComponent(Salariu3)
                                            .addComponent(Data_angajarii3)
                                            .addComponent(Nume3))
                                        .addGap(206, 206, 206)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jButton1)
                                            .addComponent(AfiseazaModele)
                                            .addComponent(AfiseazaEvenimente))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SelectEventToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumeEveniment2)
                                    .addComponent(Data2)
                                    .addComponent(Editie2)
                                    .addComponent(Locatie2)
                                    .addComponent(Tip2)
                                    .addComponent(Parteneri2))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumeEveniment3)
                                    .addComponent(Data3)
                                    .addComponent(Editie3)
                                    .addComponent(Locatie3)
                                    .addComponent(Tip3)
                                    .addComponent(Parteneri3)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumeEveniment1)
                                .addComponent(Data1)
                                .addComponent(Editie1)
                                .addComponent(Locatie1)
                                .addComponent(Tip1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(Parteneri1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nume1)
                            .addComponent(Data_nastere1)
                            .addComponent(Greutate1)
                            .addComponent(Salariu1)
                            .addComponent(Data_angajarii1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(finishAddingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addModelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EditModel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FinishEditingModel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DeleteModel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SelectModelToEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(adminPanel))
                            .addComponent(jLabel1))
                        .addContainerGap(534, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addModelButton)
                    .addComponent(SelectModelToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishAddingButton)
                    .addComponent(FinishEditingModel)
                    .addComponent(EditModel)
                    .addComponent(DeleteModel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddEvent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finishAddingEvent)
                            .addComponent(FinishEditingEvent)
                            .addComponent(EditEvent)
                            .addComponent(deleteEvent)
                            .addComponent(Refresh)))
                    .addComponent(SelectEventToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(AfiseazaModele))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nume1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Data_nastere1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Greutate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Salariu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Data_angajarii1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nume2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data_nastere2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Greutate2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salariu2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data_angajarii2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nume3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data_nastere3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Greutate3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salariu3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data_angajarii3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeEveniment3)
                            .addComponent(AfiseazaEvenimente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Editie3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Locatie3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tip3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Parteneri3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumeEveniment1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Data1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Editie1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Locatie1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tip1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Parteneri1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumeEveniment2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Data2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Editie2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Locatie2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tip2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Parteneri2))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModelButtonActionPerformed
//        	Nume = "Ion";
//	        Prenume = "Ionica";
//                CNP = "1234567890123";
//                I_tata = "L";
//                Data_nastere = "1994-05-23";
//                Oras = "Bucuresti";
//                Greutate = 77;
//                Inaltime = 170;
//                Talie = 90;
//                Bust = 60;
//                Solduri = 90;
//                Cul_par = "Saten";
//                Cul_ochi = "Caprui";
//                Nr_tel = "0876543234";
//                Data_angajarii = "2009-03-22";
//                Salariu = 1500;
//                Autocaracterizare = "Eu sunt ION!";
//
//                Nume_eveniment = "X Modelling";
//                Data = "2014-03-03";
//                Editie = 4;
//                Locatie = "Pitesti";
//                Tip = "Recrutare";
//                Descriere = "X Modells recruteaza fotomodele!";
//        
//        Command.AddModel(Nume, Prenume, CNP, I_tata, Data_nastere, Oras, Greutate, Inaltime, 
//	        		Talie, Bust, Solduri, Cul_par, Cul_ochi, Nr_tel, Data_angajarii, Salariu, Autocaracterizare);
                addModel.setVisible(true);

    }//GEN-LAST:event_addModelButtonActionPerformed

    private void finishAddingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishAddingButtonActionPerformed
        Nume = addModel.Nume.getText();
        Prenume = addModel.Prenume.getText();
        CNP = addModel.CNP.getText();
        I_tata = addModel.I_tata.getText();
        Data_nastere = addModel.Data_nastere.getText();
        Oras = addModel.Oras.getText();
        Greutate = Integer.parseInt(addModel.Greutate.getText());
        Inaltime = Integer.parseInt(addModel.Inaltime.getText());
        Talie = Integer.parseInt(addModel.Talie.getText());
        Bust = Integer.parseInt(addModel.Bust.getText());
        Solduri = Integer.parseInt(addModel.Solduri.getText());
        Cul_par = addModel.Cul_par.getText();
        Cul_ochi = addModel.Cul_ochi.getText();
        Nr_tel = addModel.Nr_tel.getText();
        Data_angajarii = addModel.Data_angajarii.getText();
        Salariu = Integer.parseInt(addModel.Salariu.getText());
        Autocaracterizare = addModel.Autocaracterizare.getText();
        
        Command.AddModel(Nume, Prenume, CNP, I_tata, Data_nastere, Oras, Greutate, Inaltime, 
			Talie, Bust, Solduri, Cul_par, Cul_ochi, Nr_tel, Data_angajarii, Salariu, Autocaracterizare);
        
        addModel.setVisible(false);
        succesMessage.setVisible(true);
    }//GEN-LAST:event_finishAddingButtonActionPerformed

    private void AddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventActionPerformed
        addEvent.setVisible(true);
    }//GEN-LAST:event_AddEventActionPerformed

    private void finishAddingEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishAddingEventActionPerformed
        Nume_eveniment = addEvent.Nume_eveniment.getText();
        Data = addEvent.Data.getText();
        Editie = Integer.parseInt(addEvent.Editie.getText());
        Locatie = addEvent.Locatie.getText();
        Tip = addEvent.Tip.getText();
        Descriere = addEvent.Descriere.getText();

        Command.AddEvent(Nume_eveniment, Data, Editie, Locatie, Tip, Descriere);
        addEvent.setVisible(false);
        succesMessage.setVisible(true);
    }//GEN-LAST:event_finishAddingEventActionPerformed

    private void EditModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditModelActionPerformed
        editModel.setVisible(true);
    }//GEN-LAST:event_EditModelActionPerformed

    private void SelectModelToEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectModelToEditActionPerformed
        editModel.setSelectedItem(SelectModelToEdit.getSelectedItem().toString());
    }//GEN-LAST:event_SelectModelToEditActionPerformed

    private void FinishEditingModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishEditingModelActionPerformed
        ID_model = Integer.parseInt(editModel.ID_model.getText());
        Nume = editModel.Nume.getText();
        Prenume = editModel.Prenume.getText();
        CNP = editModel.CNP.getText();
        I_tata = editModel.I_tata.getText();
        Data_nastere = editModel.Data_nastere.getText();
        Oras = editModel.Oras.getText();
        Greutate = Integer.parseInt(editModel.Greutate.getText());
        Inaltime = Integer.parseInt(editModel.Inaltime.getText());
        Talie = Integer.parseInt(editModel.Talie.getText());
        Bust = Integer.parseInt(editModel.Bust.getText());
        Solduri = Integer.parseInt(editModel.Solduri.getText());
        Cul_par = editModel.Cul_par.getText();
        Cul_ochi = editModel.Cul_ochi.getText();
        Nr_tel = editModel.Nr_tel.getText();
        Data_angajarii = editModel.Data_angajarii.getText();
        Salariu = Integer.parseInt(addModel.Salariu.getText());
        Autocaracterizare = editModel.Autocaracterizare.getText();
        
        Command.EditModelEditare(ID_model, Nume, Prenume, CNP, I_tata, Data_nastere, Oras, Greutate, Inaltime, 
			Talie, Bust, Solduri, Cul_par, Cul_ochi, Nr_tel, Data_angajarii, Salariu, Autocaracterizare);
        
        editModel.setVisible(false);
        succesMessage.setVisible(true);
    }//GEN-LAST:event_FinishEditingModelActionPerformed

    private void EditEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEventActionPerformed
        editEvent.setVisible(true);
    }//GEN-LAST:event_EditEventActionPerformed

    private void FinishEditingEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishEditingEventActionPerformed
        
        ID_eveniment = Integer.parseInt(editEvent.ID_eveniment.getText());
        Nume_eveniment = editEvent.Nume_eveniment.getText();
        Data = editEvent.Data.getText();
        Editie = Integer.parseInt(editEvent.Editie.getText());
        Locatie = editEvent.Locatie.getText();
        Tip = editEvent.Tip.getText();
        Descriere = editEvent.Descriere.getText();
        
        Command.EditEventEditare(ID_eveniment, Nume_eveniment, Data, Editie, Locatie, Tip, Descriere);
        
        editEvent.setVisible(false);
        succesMessage.setVisible(true);
    }//GEN-LAST:event_FinishEditingEventActionPerformed

    private void SelectEventToEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectEventToEditActionPerformed
        editEvent.setSelectedItem(SelectEventToEdit.getSelectedItem().toString());
    }//GEN-LAST:event_SelectEventToEditActionPerformed

    private void DeleteModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteModelActionPerformed
        String delims = "[ ]+";
        String[] tokens = SelectModelToEdit.getSelectedItem().toString().split(delims);
        Command.DeleteModel(Integer.parseInt(tokens[0]));
        succesMessage.setVisible(true);
    }//GEN-LAST:event_DeleteModelActionPerformed

    private void deleteEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEventActionPerformed
        String delims = "[ ]+";
        String[] tokens = SelectEventToEdit.getSelectedItem().toString().split(delims);
        Command.DeleteEvent(Integer.parseInt(tokens[0]));
        succesMessage.setVisible(true);
    }//GEN-LAST:event_deleteEventActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
       int i = 0;
        ListOfSelectedModels = new String[6];
        ListOfSelectedEvents = new String[6];
        ResultSet res = Command.CustomQuery("SELECT ID_model, Nume, Prenume FROM `model`");
        try {
            while (res.next()){
                ListOfSelectedModels[i] = res.getString("ID_model") + " " + res.getString("Nume") + " " + res.getString("Prenume") + ", ";
                i++;
            }
        }catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
         }
        SelectModelToEdit.setModel(new javax.swing.DefaultComboBoxModel<>(ListOfSelectedModels));
        
        int j = 0;

        ResultSet ress = Command.CustomQuery("SELECT ID_eveniment, Nume FROM `evenimente`");
        try {
            while (ress.next()){
                ListOfSelectedEvents[j] = ress.getString("ID_eveniment") + " " + ress.getString("Nume") + ", ";
                j++;
            }
        }catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
         }
        SelectEventToEdit.setModel(new javax.swing.DefaultComboBoxModel<>(ListOfSelectedEvents));
    }//GEN-LAST:event_RefreshActionPerformed

    private void adminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPanelActionPerformed
        adminLoginPanel.setVisible(true);
    }//GEN-LAST:event_adminPanelActionPerformed

    private void AfiseazaModeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfiseazaModeleActionPerformed
       
    try {
        int j = 0;
        ResultSet res = Command.CustomQuery("SELECT * FROM `model`");

        res.next();

        Nume1.setText("Nume: " + res.getString("Nume") + " " + res.getString("Prenume"));
        Data_nastere1.setText("Data nasterii: " + res.getString("Data_nastere"));
        Greutate1.setText("Greutate: " + res.getString("Greutate"));
        Salariu1.setText("Salariu: " + res.getString("Salariu"));
        Data_angajarii1.setText("Data angajarii: " + res.getString("Data_angajarii"));
        
        res.next();
        Nume2.setText("Nume: " + res.getString("Nume") + " " + res.getString("Prenume"));
        Data_nastere2.setText("Data nasterii: " + res.getString("Data_nastere"));
        Greutate2.setText("Greutate: " + res.getString("Greutate"));
        Salariu2.setText("Salariu: " + res.getString("Salariu"));
        Data_angajarii2.setText("Data angajarii: " + res.getString("Data_angajarii"));
        
        res.next();
        Nume3.setText("Nume: " + res.getString("Nume") + " " + res.getString("Prenume"));
        Data_nastere3.setText("Data nasterii: " + res.getString("Data_nastere"));
        Greutate3.setText("Greutate: " + res.getString("Greutate"));
        Salariu3.setText("Salariu: " + res.getString("Salariu"));
        Data_angajarii3.setText("Data angajarii: " + res.getString("Data_angajarii"));
        
    } catch (SQLException ex) {
        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_AfiseazaModeleActionPerformed

    private void AfiseazaEvenimenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfiseazaEvenimenteActionPerformed
        try {
        int j = 0;
        ResultSet res = Command.CustomQuery("SELECT * FROM `Evenimente`");
        ResultSet res2 = Command.CustomQuery("SELECT e.Nume, COUNT(Nume_partener) AS Numar_parteneri FROM parteneri_evenimente pe, evenimente e WHERE e.ID_eveniment = pe.ID_eveniment GROUP BY e.ID_eveniment");
        
        res.next();
        res2.next();
        NumeEveniment1.setText("Nume: " + res.getString("Nume"));
        Data1.setText("Data: " + res.getString("Data"));
        Editie1.setText("Editie: " + res.getString("Editie"));
        Locatie1.setText("Locatie: " + res.getString("Locatie"));
        Tip1.setText("Tip: " + res.getString("Tip"));
        Parteneri1.setText("Parteneri: " + res2.getString("Numar_parteneri"));
        
        res.next();
        res2.next();
        NumeEveniment2.setText("Nume: " + res.getString("Nume"));
        Data2.setText("Data: " + res.getString("Data"));
        Editie2.setText("Editie: " + res.getString("Editie"));
        Locatie2.setText("Locatie: " + res.getString("Locatie"));
        Tip2.setText("Tip: " + res.getString("Tip"));
        Parteneri2.setText("Parteneri: " + res2.getString("Numar_parteneri"));
        
        res.next();
        res2.next();
        NumeEveniment3.setText("Nume: " + res.getString("Nume"));
        Data3.setText("Data: " + res.getString("Data"));
        Editie3.setText("Editie: " + res.getString("Editie"));
        Locatie3.setText("Locatie: " + res.getString("Locatie"));
        Tip3.setText("Tip: " + res.getString("Tip"));
        Parteneri3.setText("Parteneri: " + res2.getString("Numar_parteneri"));
        
    } catch (SQLException ex) {
        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_AfiseazaEvenimenteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        ResultSet res = Command.CustomQuery("SELECT DISTINCT part.Nume_partener, m.Inaltime, p.Tip_parteneriat " +
"FROM parteneri_evenimente part, participare p, model m " +
"WHERE part.ID_eveniment = p.ID_eveniment AND m.ID_model=p.ID_model HAVING m.Inaltime = (SELECT MAX(Inaltime) FROM model m1 WHERE m1.ID_model = m.ID_model )");

        res.next();

        Nume1.setText("Nume: " + res.getString("Nume_partener"));
        Data_nastere1.setText("Tip parteneriat " + res.getString("Tip_parteneriat"));
        Greutate1.setText("Inaltimea modelului: " + res.getString("Inaltime"));
        Salariu1.setText("");
        Data_angajarii1.setText("");
        
        Nume2.setText("");
        Data_nastere2.setText("");
        Greutate2.setText("");
        Salariu2.setText("");
        Data_angajarii2.setText("");
        
        
        Nume3.setText("");
        Data_nastere3.setText("");
        Greutate3.setText("");
        Salariu3.setText("");
        Data_angajarii3.setText("");
        
        } catch (SQLException ex) {
        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
                
        try{
	        String url = "jdbc:mysql://localhost:3306/";
	        String user = "root";
	        String password = "minimmaxim";   // O sa fac un frame in care utilizatorul iintroduce userul si parola
	        
	        Command.Connect(url,user,password); // verifica pe net ce returneaza functia ca sa faci un mesaj de eroare
	      
            //ResultSet resultInterogareModel = Command.EditModelInterogare(/*cevaceva*/);

	        /* Aici variabilele alea primesc valori de la use prin interfata jframe
	        * Mai jos vom simula acest lucru 
	        */

			//
	        
			
			//
	        //Command.AddModel(Nume, Prenume, CNP, I_tata, Data_nastere, Oras, Greutate, Inaltime, 
	        //		Talie, Bust, Solduri, Cul_par, Cul_ochi, Nr_tel, Data_angajarii, Salariu, Autocaracterizare);
	        
			
			//
	        //Command.AddEvent(Nume_eveniment, Data, Editie, Locatie, Tip, Descriere);
	        //
			
			//
	        //ID_model = 1;
	        //ID_eveniment = 1;
	        //ResultSet rezultatInterogareEditare = Command.EditModelInterogare(ID_model)	;	
	        
	        /*	
	        // Testare concept result test
	        //
	        while (rezultatInterogareEditare.next())
            {
		        System.out.println(rezultatInterogareEditare.getString("ID_model") + " " + rezultatInterogareEditare.getString("Nume") + " " + 
		        		rezultatInterogareEditare.getString("CNP") + " " + rezultatInterogareEditare.getString("I_tata") + " " + 
		        		rezultatInterogareEditare.getString("Data_nastere") + " " + rezultatInterogareEditare.getString("Oras") + " " + 
		        		rezultatInterogareEditare.getString("Greutate") + " " + rezultatInterogareEditare.getString("Inaltime") + " " + 
		        		rezultatInterogareEditare.getString("Talie") + " " + rezultatInterogareEditare.getString("Bust") + " " + 
		        		rezultatInterogareEditare.getString("Solduri") + " " + rezultatInterogareEditare.getString("Cul_par") + " " + 
		        		rezultatInterogareEditare.getString("Cul_ochi") + " " + rezultatInterogareEditare.getString("Nr_tel") + " " +
		        		rezultatInterogareEditare.getString("Data_angajarii") + " " + rezultatInterogareEditare.getString("Salariu") + " " + 
		        		rezultatInterogareEditare.getString("Autocaracterizare"));
            }
	        // Afisarea result test-ului functioneaza!
	        */
	   
	        //
	        //Command.EditModelEditare(ID_model, Nume, Prenume, CNP, I_tata, Data_nastere, Oras, Greutate, Inaltime, 
	        //		Talie, Bust, Solduri, Cul_par, Cul_ochi, Nr_tel, Data_angajarii, Salariu, Autocaracterizare);
	        //
	        
	        //
	        //Command.DeleteModel(ID_model);
	        //
	        
	        //
	        //Command.DeleteEvent(ID_eveniment);
	        //

	        //
	        //Command.Disconnect();
	        //

	    }
	    catch (Exception e)
	    {
	    	e.printStackTrace();
	    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEvent;
    private javax.swing.JButton AfiseazaEvenimente;
    private javax.swing.JButton AfiseazaModele;
    private javax.swing.JLabel Data1;
    private javax.swing.JLabel Data2;
    private javax.swing.JLabel Data3;
    private javax.swing.JLabel Data_angajarii1;
    private javax.swing.JLabel Data_angajarii2;
    private javax.swing.JLabel Data_angajarii3;
    private javax.swing.JLabel Data_nastere1;
    private javax.swing.JLabel Data_nastere2;
    private javax.swing.JLabel Data_nastere3;
    private javax.swing.JButton DeleteModel;
    private javax.swing.JButton EditEvent;
    private javax.swing.JButton EditModel;
    private javax.swing.JLabel Editie1;
    private javax.swing.JLabel Editie2;
    private javax.swing.JLabel Editie3;
    private javax.swing.JButton FinishEditingEvent;
    private javax.swing.JButton FinishEditingModel;
    private javax.swing.JLabel Greutate1;
    private javax.swing.JLabel Greutate2;
    private javax.swing.JLabel Greutate3;
    private javax.swing.JLabel Locatie1;
    private javax.swing.JLabel Locatie2;
    private javax.swing.JLabel Locatie3;
    private javax.swing.JLabel Nume1;
    private javax.swing.JLabel Nume2;
    private javax.swing.JLabel Nume3;
    private javax.swing.JLabel NumeEveniment1;
    private javax.swing.JLabel NumeEveniment2;
    private javax.swing.JLabel NumeEveniment3;
    private javax.swing.JLabel Parteneri1;
    private javax.swing.JLabel Parteneri2;
    private javax.swing.JLabel Parteneri3;
    private javax.swing.JButton Refresh;
    private javax.swing.JLabel Salariu1;
    private javax.swing.JLabel Salariu2;
    private javax.swing.JLabel Salariu3;
    private javax.swing.JComboBox<String> SelectEventToEdit;
    private javax.swing.JComboBox<String> SelectModelToEdit;
    private javax.swing.JLabel Tip1;
    private javax.swing.JLabel Tip2;
    private javax.swing.JLabel Tip3;
    private javax.swing.JButton addModelButton;
    private javax.swing.JButton adminPanel;
    private javax.swing.JButton deleteEvent;
    private javax.swing.JButton finishAddingButton;
    private javax.swing.JButton finishAddingEvent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
